config/routes.rb
Rails.application.routes.draw do
  resources :breeds, only: %i(index show)

  root "breeds#index"

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  include BreedsHelper

  before_action :set_breeds

  def index; end

  def show
    breed = params[:id].gsub('-', '/')
    @breed = RedisCache.fetch(breed, CACHE_MINUTES) do
      BreedsFetcher.random_image(breed)
    end
    @breed = OpenStruct.new(@breed)
  end

  protected

  def format_breeds(breeds)
    new_breeds = []
    breeds.each do |breed, subbreeds|
      if subbreeds.blank?
        new_breeds.push breed
      else 
        new_breeds = new_breeds.concat(subbreeds.map { |sub| "#{breed}/#{sub}" })
      end
    end
    new_breeds
  end

  private

  def set_breeds
    @breeds = RedisCache.fetch('breeds', CACHE_MINUTES) do
      format_breeds(BreedsFetcher.fetch)
    end
  end
end

app/controllers/concerns/redis_cache.rb
module RedisCache
  extend ActiveSupport::Concern

  def self.fetch(key, expire = 1)
    redis_value = self.get(key)
    
    if redis_value
      JSON.parse(redis_value)
    else
      result = yield
      err = REDIS.set(key, result.to_json, ex: expire)
      result
    end
  end

  def self.get(key)
    REDIS.get(key)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
  def humanize(name)
    name.split('/').reverse.map(&:classify).join(' ')
  end
end

app/views/breeds/_list.html.erb
<div>
  <%- breeds.each do |breed| %>
    <% formated_breed = breed.gsub('/', '-') %>
    <h3>
      <%= link_to humanize(breed), "#{breeds_path}/#{formated_breed}", data: { turbolinks_scroll: false}, class: params[:id] == formated_breed ? 'active' : '' %>
    </h3>
  <% end %>
</div>

app/views/breeds/index.html.erb
<%= render 'list', breeds: @breeds %>

app/views/breeds/show.html.erb
  <div class="columns">
    <div class="column turbolinks-disable-scroll">
      <%= render 'list', breeds: @breeds %>
    </div>
    <div class="column">
      <div class="card" style="position: fixed;">
        <div class="card-image">
          <figure class="image">
            <%= image_tag @breed.image_url %>
          </figure>
        </div>
        <div class="card-content">
          <h2 class="subtitle">
            <%= humanize(@breed.breed) %>
          </h2>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="section">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>